name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - uses: microsoft/setup-msbuild@v1
    - uses: NuGet/setup-nuget@v1.0.5

    - name: Restore NuGet packages
      run: nuget restore NHtmlUnit.sln

    - uses: gittools/actions/gitversion/setup@v0.9.9
      with:
        versionSpec: '5.x.x'

    - uses: gittools/actions/gitversion/execute@v0.9.9
      id: gitversion # step id used as reference for output values
      with:
        updateAssemblyInfo: true

    - name: Build Solution
      run: msbuild NHtmlUnit.sln /property:Configuration=Release

    - name: Test Solution
      run: packages\NUnit.ConsoleRunner.3.12.0\tools\nunit3-console.exe tests\IntegrationTests\bin\Release\IntegrationTests.dll

    - name: Create NuGet Package
      run: nuget.exe pack NHtmlUnit.nuspec -Verbosity detailed -Symbols -Properties Configuration=Release -Version ${{ steps.gitversion.outputs.nuGetVersion }}

    - uses: actions/upload-artifact@v2
      with:
        name: NHtmlUnit.nupkg
        path: '*.nupkg'

  publish:
    runs-on: windows-latest
    needs: build

    steps:
    - uses: actions/download-artifact@v2
      with:
        name: NHtmlUnit.nupkg

    - uses: NuGet/setup-nuget@v1.0.5

    - name: Publish To NuGet.org
      # if: startsWith(github.ref, 'refs/tags/') # Only publish tagged commits
      run: nuget push *.nupkg -Source nuget.org -ApiKey ${{ secrets.NUGET_API_KEY }}
